---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaoyouwen.
--- DateTime: 2019-09-02 06:26
---
local uri_args = ngx.req.get_uri_args()
local productId = uri_args["productId"]

local host={"192,168.0.106","192.168.0.107"}
local hash = ngx.crc32_long(productId)
hash = (hash%2)+1
backend = "http://"..host[hash]

local method = uri_args["method"];
local requestBody = "/"..method.."productId="..productId

local http = require("resty.http")
local httpc = http.new();


